# Generated by Django 4.1.7 on 2023-03-23 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('email', models.EmailField(default='none@email.com', max_length=254)),
                ('first_name', models.CharField(default='', max_length=248)),
                ('blood_type', models.CharField(max_length=200)),
                ('date_of_last_appointment', models.CharField(max_length=200)),
                ('allergies', models.CharField(max_length=200)),
                ('medication', models.CharField(max_length=500)),
                ('medical_condition', models.CharField(max_length=500)),
                ('test_and_procedures', models.CharField(max_length=1000)),
                ('date_of_diagnosis', models.DateField(max_length=500)),
                ('doctors_notes', models.CharField(max_length=1000)),
                ('next_appointment', models.DateField(max_length=500)),
                ('stomach_ache', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('malaria', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('injuries', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('head_ache', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('cough', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('fever', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
