# Generated by Django 4.1.7 on 2023-03-23 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_medicalrecord_delete_profile_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
