# Generated by Django 4.1.7 on 2023-03-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='cough',
            field=models.IntegerField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='fever',
            field=models.IntegerField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='head_ache',
            field=models.IntegerField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='injuries',
            field=models.IntegerField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='malaria',
            field=models.IntegerField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='stomach_ache',
            field=models.IntegerField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255),
        ),
    ]
